import json
import os
import urllib.request
import urllib.parse
import math
from collections import defaultdict
from xml.sax.saxutils import escape

TOKEN = os.environ["LANGUAGE_STATS_TOKEN"]
USERNAME = "jvribe"
API = "https://api.github.com"


def api_get(path, params=None):
    url = API + path
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "jvribe-language-stats",
    })
    with urllib.request.urlopen(req) as response:
        return json.load(response)


repos = []
page = 1
while True:
    batch = api_get("/user/repos", {
        "visibility": "all",
        "affiliation": "owner",
        "per_page": 100,
        "page": page,
        "sort": "updated",
    })
    if not batch:
        break
    repos.extend(batch)
    if len(batch) < 100:
        break
    page += 1

languages = defaultdict(int)
for repo in repos:
    if repo.get("owner", {}).get("login", "").lower() != USERNAME.lower():
        continue
    if repo.get("fork") or repo.get("archived"):
        continue
    try:
        data = api_get(f"/repos/{USERNAME}/{repo['name']}/languages")
        for language, bytes_count in data.items():
            languages[language] += bytes_count
    except Exception as exc:
        print(f"Skipping {repo['name']}: {exc}")

languages = dict(sorted(languages.items(), key=lambda item: item[1], reverse=True))
total = sum(languages.values())
if not total:
    raise SystemExit("No language data found.")

items = []
for language, value in languages.items():
    percent = value / total * 100
    if percent >= 0.5:
        items.append((language, percent))

if len(items) > 10:
    other = sum(p for _, p in items[9:])
    items = items[:9] + [("Other", other)]

palette = [
    "#3178C6", "#F7DF1E", "#ED8B00", "#3776AB", "#6DB33F",
    "#E34F26", "#563D7C", "#61DAFB", "#8B5CF6", "#A78BFA"
]

width, height = 720, 330
cx, cy, radius, inner_radius = 150, 175, 105, 64

svg = [
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
    '<rect width="100%" height="100%" rx="16" fill="#0d1117"/>',
    '<text x="28" y="38" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif" font-size="18" font-weight="700">Languages across my repositories</text>',
    f'<circle cx="{cx}" cy="{cy}" r="{radius}" fill="#21262d"/>',
]

start_angle = -90
for i, (language, percent) in enumerate(items):
    angle = percent / 100 * 360
    end_angle = start_angle + angle
    large_arc = 1 if angle > 180 else 0

    def point(r, a):
        rad = math.radians(a)
        return cx + r * math.cos(rad), cy + r * math.sin(rad)

    x1, y1 = point(radius, start_angle)
    x2, y2 = point(radius, end_angle)
    x3, y3 = point(inner_radius, end_angle)
    x4, y4 = point(inner_radius, start_angle)
    color = palette[i % len(palette)]

    path = (
        f'M {x1:.2f},{y1:.2f} '
        f'A {radius},{radius} 0 {large_arc},1 {x2:.2f},{y2:.2f} '
        f'L {x3:.2f},{y3:.2f} '
        f'A {inner_radius},{inner_radius} 0 {large_arc},0 {x4:.2f},{y4:.2f} Z'
    )
    svg.append(f'<path d="{path}" fill="{color}"/>')
    start_angle = end_angle

svg.append(f'<circle cx="{cx}" cy="{cy}" r="{inner_radius - 1}" fill="#0d1117"/>')
svg.append(f'<text x="{cx}" y="{cy - 4}" text-anchor="middle" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif" font-size="20" font-weight="700">{len(items)}</text>')
svg.append(f'<text x="{cx}" y="{cy + 16}" text-anchor="middle" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="11">languages</text>')

legend_x = 305
legend_y = 78
for i, (language, percent) in enumerate(items):
    y = legend_y + i * 24
    color = palette[i % len(palette)]
    svg.append(f'<circle cx="{legend_x}" cy="{y - 4}" r="5" fill="{color}"/>')
    svg.append(f'<text x="{legend_x + 16}" y="{y}" fill="#c9d1d9" font-family="Arial,Helvetica,sans-serif" font-size="14">{escape(language)}</text>')
    svg.append(f'<text x="680" y="{y}" text-anchor="end" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="14">{percent:.1f}%</text>')

svg.append(f'<text x="28" y="{height - 16}" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="11">Public + private • own non-forked repositories • generated by GitHub Actions</text>')
svg.append('</svg>')

os.makedirs("assets", exist_ok=True)
with open("assets/github-languages.svg", "w", encoding="utf-8") as file:
    file.write("\n".join(svg))

print(f"Processed {len(repos)} accessible repositories; generated {len(items)} language entries.")
