import json
import os
import urllib.request
import urllib.parse
from collections import defaultdict
from xml.sax.saxutils import escape

TOKEN = os.environ["LANGUAGE_STATS_TOKEN"]
USERNAME = "jvribe"
API = "https://api.github.com"


def api_get(path, params=None):
    url = API + path
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "jvribe-language-stats",
    })
    with urllib.request.urlopen(req) as response:
        return json.load(response)


repos = []
page = 1
while True:
    batch = api_get("/user/repos", {
        "visibility": "all",
        "affiliation": "owner",
        "per_page": 100,
        "page": page,
        "sort": "updated",
    })
    if not batch:
        break
    repos.extend(batch)
    if len(batch) < 100:
        break
    page += 1

languages = defaultdict(int)
for repo in repos:
    if repo.get("owner", {}).get("login", "").lower() != USERNAME.lower():
        continue
    if repo.get("fork") or repo.get("archived"):
        continue
    try:
        data = api_get(f"/repos/{USERNAME}/{repo['name']}/languages")
        for language, bytes_count in data.items():
            languages[language] += bytes_count
    except Exception as exc:
        print(f"Skipping {repo['name']}: {exc}")

languages = dict(sorted(languages.items(), key=lambda item: item[1], reverse=True))
total = sum(languages.values())
if not total:
    raise SystemExit("No language data found.")

items = []
for language, value in languages.items():
    percent = value / total * 100
    if percent >= 0.5:
        items.append((language, percent))

# Keep the widget readable while preserving all meaningful languages.
if len(items) > 10:
    other = sum(p for _, p in items[9:])
    items = items[:9] + [("Other", other)]

palette = ["#3178C6", "#F7DF1E", "#ED8B00", "#3776AB", "#6DB33F", "#E34F26", "#563D7C", "#61DAFB", "#000000", "#8B5CF6"]
width, height = 720, 310
bar_x, bar_w, bar_h = 24, 410, 18
start_y = 70

svg = [
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
    '<rect width="100%" height="100%" rx="14" fill="#0d1117"/>',
    '<text x="24" y="36" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif" font-size="18" font-weight="700">Languages across my repositories</text>',
]

for i, (language, percent) in enumerate(items):
    y = start_y + i * 23
    bar_width = max(2, bar_w * percent / 100)
    color = palette[i % len(palette)]
    svg.append(f'<rect x="{bar_x}" y="{y}" width="{bar_w}" height="{bar_h}" rx="9" fill="#21262d"/>')
    svg.append(f'<rect x="{bar_x}" y="{y}" width="{bar_width:.1f}" height="{bar_h}" rx="9" fill="{color}"/>')
    svg.append(f'<text x="460" y="{y + 14}" fill="#c9d1d9" font-family="Arial,Helvetica,sans-serif" font-size="14">{escape(language)}</text>')
    svg.append(f'<text x="680" y="{y + 14}" text-anchor="end" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="14">{percent:.1f}%</text>')

svg.append(f'<text x="24" y="{height - 16}" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="11">Public + private • own non-forked repositories • generated by GitHub Actions</text>')
svg.append('</svg>')

os.makedirs("assets", exist_ok=True)
with open("assets/github-languages.svg", "w", encoding="utf-8") as file:
    file.write("\n".join(svg))

print(f"Processed {len(repos)} accessible repositories; generated {len(items)} language entries.")
